### PR TITLE
terminaltables 3.1.7, update to new upstream URLs, download license, pip check, maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- alternative to #1 
- partially unblocks https://github.com/conda-forge/jake-feedstock/pull/7#issuecomment-987921197
- adds `pip check`
- adds self as maintainer

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/terminaltables ready for review, i guess? not sure if `jake` will be keeping this as a long-term dep, which appears to be the motivating case for the new maintainer...

**Comment by bollwyvl** [comment]
Hooray #1

**Comment by ocefpaf** [comment]
Oh. Missed this one! It would be nice to add you as a maintainer here.

**Pull request closed without merging**
